-- insert into actor
-- values(10001,'Sherlock Holmes');
-- insert into actor
-- values(10002,'Dr. Watson');
-- insert into actor
-- values(10003,'Inspector Lestrade');
-- insert into actor
-- values(10004,'Mrs. Hudson');
-- insert into actor
-- values(10005,'One Irregular Kid');
-- insert into actor 
-- values(10006,'Irene Adler');

-- insert into speaker
-- values(1,'Greg','PORTFOLIOA',10006);
-- insert into speaker
-- values(2,'Basil','PORTFOLIOB',10005);
-- insert into speaker 
-- values (3, 'Peter','PORTFOLIOC',10004);